accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_pk>/', views.profile, name='profile'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

django_pjt5/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views as movies_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('', movies_views.index),
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('', views.index, name="index"),

    path('movie_create/', views.movie_create, name='movie_create'),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/movie_like/', views.movie_like, name='movie_like')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=20)
    poster_path = models.CharField(max_length=100)
    backdrop_path = models.CharField(max_length=100, blank=True)
    genres = models.ManyToManyField(Genre, related_name='movies')
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']

movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_POST

from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

def profile(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    context = {
        'user' : user
    }
    return render(request, 'accounts/profile.html', context)

def follow(request, user_pk):
    User = get_user_model()
    user=get_object_or_404(User, pk=user_pk)
    if user.followers.filter(pk=request.user.pk).exists():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)
    return redirect('accounts:profile', user.pk)

@require_POST
@login_required
def delete(request):
    request.user.delete()
    return redirect('movies:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context={
        'form':form
    }
    return render(request, 'accounts/update.html', context)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.paginator import Paginator
import random


from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movies = Movie.objects.order_by('-release_date')
    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    ranmv = random.choices(movies, k=10)

    context = {
        'movies':movies,
        'page_obj': page_obj,
        'ranmv': ranmv,
    }

    return render(request, 'movies/index.html', context)

@login_required
def movie_create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:movie_detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form
    }
    return render(request, 'movies/forms.html', context)

def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)



def movie_like(request, movie_pk):
    user = request.user
    movie = get_object_or_404(Movie, pk=movie_pk)

    if movie.like_user.filter(pk=user.pk).exists():
        movie.like_user.remove(user)
        liked = False
    else:
        movie.like_user.add(user)
        liked = True
    context = {
        'liked': liked,
        'count': movie.like_user.count()
    }
    return JsonResponse(context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}


{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-secondary">로그인</button>
    <a href="{% provider_login_url 'google' %}" class="btn btn-primary">GOOGLE LOGIN</a>


</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Profile{% endblock %}

{% block content %}
<h1>{{ user.username }}</h1>
<hr>
<p>팔로워 : {{ user.followers.count }}명</p>
<p>팔로잉 : {{ user.followings.count }}명</p>
{% if request.user.is_authenticated %}
    {% if request.user == user %}
        <a href="{% url 'accounts:update' %}"><button class="btn btn-secondary">회원 수정</button></a>
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-danger">회원 탈퇴</button>
        </form>
    {% else %}
        {% if request.user in user.followers.all %}
            <a href="{% url 'accounts:follow' user.pk %}"><i class="fas fa-user-check fa-2x"></i></a>
        {% else %}
            <a href="{% url 'accounts:follow' user.pk %}"><i class="fas fa-user-plus fa-2x"></i></a>
        {% endif %}
    {% endif %}
{% endif %}
<hr>
<h3>{{ user.username }}님이 작성한 리뷰 | {{ user.reviews.count }}개</h3>
{% for review in user.reveiws.all %}
    <p>제목 : {{ review.title }} ({{ review.comments.count }}</p>
    <p>영화 제목 : {{ review.movie_title }}</p>
    <p>좋아요 : {{ review.like_reviews.count }}명</p>
    <hr>
{% endfor %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h1>Sign Up</h1>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-secondary">회원가입</button>
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}User{% endblock %}

{% block content %}
<h1>Modify Profile</h1>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-secondary">수정</button>
</form>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}{{ movie.title }}{% endblock %}

{% block content %}
<h1>{{ movie.title }}</h1>
<h3>{{ movie.original_title }}</h3>
{% for g in movie.genres.all %}
{{ g.name }},
{% endfor %}
<p class="text-right">{{ movie.release_date }}</p>
<p>{{ movie.overview }}</p>

{% if request.user.is_authenticated %}
  {% if request.user in movie.like_user.all %}
  <i class="fas fa-heart fa-lg like-buttons" style="color:crimson" data-id="{{ movie.pk }}"></i>
  {% else %}
  <i class="fas fa-heart fa-lg like-buttons" style="color:black" data-id="{{ movie.pk }}"></i>
  {% endif %}
{% endif %}
<span id="like-count-{{ movie.pk }}">{{ movie.like_user.all|length }}</span> 명이 이 글을 좋아합니다.


<script>
  const likeButtonList = document.querySelectorAll('.like-buttons')

  likeButtonList.forEach(likeButton => {
    likeButton.addEventListener('click', e => {
      const movidID = e.target.dataset.id

      {% if user.is_authenticated %}
      axios.get(`/movies/${movidID}/movie_like/`)
      .then(res => {
          document.querySelector(`#like-count-${movidID}`).innerText = res.data.count
          if (res.data.liked) {
            e.target.style.color = 'crimson'
          } else {
            e.target.style.color = 'black'
          }
        })
      {% else %}
        alert('로그인이 필요합니다.')
      {% endif %}
    })
  })
</script>


{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
<h2>추천 영화!</h2>
<div class="row row-cols-1 row-cols-md-3">
{% for rm in ranmv %}
  <div class="col-2.5 m-2">
    <div class="card" style="height:300px;">
        <a href="{% url 'movies:movie_detail' rm.pk %}"><img src="https://image.tmdb.org/t/p/w342{{ rm.poster_path }}" style="height:300px;"></a>
    </div>
  </div>
{% endfor %}
</div>
<hr>
<h2>영화 LIST</h2>
<div class="row row-cols-1 row-cols-md-3">
{% for movie in page_obj %}
  <div class="col-3 mb-4">
    <div class="card" style="height:400px;">
        <a href="{% url 'movies:movie_detail' movie.pk %}"><img src="https://image.tmdb.org/t/p/w342{{ movie.poster_path }}" style="height:400px;"></a>
    </div>
  </div>
{% endfor %}
</div>

{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}


{% endblock %}

templates/base.html
<!doctype html>
{% load bootstrap4 %}

<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Movie | {% block title %} {% endblock %}</title>

    {% bootstrap_css %}

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/70bfc8ab18.js" crossorigin="anonymous"></script>

    <!-- axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'movies:index' %}">Movies</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href=""> {{ request.user.username }} </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mt-3">
        {% block content %}
        {% endblock %}
    </div>

    {% bootstrap_javascript jquery='full' %}

  </body>
</html>